AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-ai-chatbot

  Sample SAM Template for serverless-ai-chatbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11 #Changing from Python 3.14 to 3.11
      MemorySize: 256 #Added memory size property
      Policies:
      - Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource:
              - arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-haiku-20240307-v1:0
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::serverless-ai-chatbot-rag
              - arn:aws:s3:::serverless-ai-chatbot-rag/*
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post # Changing from get to post
            Auth:
              ApiKeyRequired: true # This will tell API Gateway to reject all requests unless an API key is present
  #Adding the API Usage Plan (Throttling + Quota)
  HelloWorldApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: ServerlessAIChatbotUsagePlan
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Throttle:
        RateLimit: 5     # requests per second
        BurstLimit: 10
      Quota:
        Limit: 100       # requests per day
        Period: DAY
  # Adding an API key resource
  HelloWorldApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: ServerlessAIChatbotKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ServerlessRestApi
          StageName: Prod
  # Atttaching API key to the usage plan
  HelloWorldUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref HelloWorldApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref HelloWorldApiUsagePlan



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
